/**
 * Generates the shared GLSL color constants from @eugene-khyst/artistassistapp-color-mixer, so the
 * shaders and the TypeScript conversions cannot drift apart.
 * Output: src/services/image/filter/glsl/color-constants.glsl
 *
 * Usage: npm run generate:glsl-constants, or npm run generate:glsl-constants:check.
 * With --check the file is not written and the result is compared with the committed one.
 */

import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

import {
  D65_XYZ,
  LINEAR_RGB_TO_LMS,
  LINEAR_RGB_TO_LUMINANCE,
  LINEAR_RGB_TO_XYZ,
  LMS_TO_LINEAR_RGB,
  LMS_TO_OKLAB,
  OKLAB_TO_LMS,
  XYZ_TO_LINEAR_RGB,
} from '@eugene-khyst/artistassistapp-color-mixer';

const OUTPUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'services',
  'image',
  'filter',
  'glsl',
  'color-constants.glsl'
);

type Row = readonly [number, number, number];

/** GLSL has no implicit int, so a whole number needs a decimal point. */
function toFloat(value: number): string {
  return Number.isInteger(value) ? value.toFixed(1) : String(value);
}

/** GLSL takes mat3 in column order, so each triple below is one input channel. */
function toMat3(rows: readonly Row[]): string {
  return `mat3(${[0, 1, 2].flatMap(column => rows.map(row => toFloat(row[column]!))).join(', ')})`;
}

function toVec3(values: Row): string {
  return `vec3(${values.map(toFloat).join(', ')})`;
}

const generated = `// Generated by scripts/generate-glsl-constants.ts. Do not edit.
// Every value comes from @eugene-khyst/artistassistapp-color-mixer, so the shaders and the
// TypeScript conversions cannot drift apart.

const mat3 LINEAR_RGB_TO_XYZ = ${toMat3(LINEAR_RGB_TO_XYZ)};
const mat3 XYZ_TO_LINEAR_RGB = ${toMat3(XYZ_TO_LINEAR_RGB)};

/** The colorimetric D65 white, the row sums of the matrix above. */
const vec3 D65_XYZ = ${toVec3(D65_XYZ)};

/** Luminance is the Y row of the matrix above, so it gives the same answer. */
const vec3 LINEAR_RGB_TO_LUMINANCE = ${toVec3(LINEAR_RGB_TO_LUMINANCE)};

const mat3 LINEAR_RGB_TO_LMS = ${toMat3(LINEAR_RGB_TO_LMS)};
const mat3 LMS_TO_OKLAB = ${toMat3(LMS_TO_OKLAB)};
const mat3 OKLAB_TO_LMS = ${toMat3(OKLAB_TO_LMS)};
const mat3 LMS_TO_LINEAR_RGB = ${toMat3(LMS_TO_LINEAR_RGB)};
`;

if (process.argv.includes('--check')) {
  if (readFileSync(OUTPUT, 'utf8') !== generated) {
    throw new Error(`${OUTPUT} is out of date, run npm run generate:glsl-constants`);
  }
  console.log(`up to date: ${OUTPUT}`);
} else {
  writeFileSync(OUTPUT, generated);
  console.log(`written: ${OUTPUT}`);
}
